name: Publish docs for Capture SDK
permissions:
  contents: write
on:
  push:
    tags:
      - 'GiniCaptureSDK;[0-9]+.[0-9]+.[0-9]+;doc**'
  workflow_call:
  workflow_dispatch:

jobs:
  release-documentation:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '16.4'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get branch name
      id: branch
      shell: bash
      run: |
        # Get the branch ref that contains the tag in github.ref
        # (github.ref contains the tag because this workflow is triggered by tags: 
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
        branch_ref=$(git branch -r --contains "${{ github.ref }}")
        # Remove "origin/" prefix from branch_ref and trim whitespace
        branch_name=$(echo ${branch_ref/origin\/} | tr -d '[:space:]')
        echo "{branch_name}={branch_name}" >> $GITHUB_OUTPUT
        echo "branch_name: $branch_name"

    - name: setup ruby
      uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.245.0
      with:
        ruby-version: '3.2.0'
        bundler-cache: true
        
    - name: Generate a token
      id: generate-token
      # available args: https://github.com/actions/create-github-app-token?tab=readme-ov-file
      uses: actions/create-github-app-token@064492a9a1762067169d50c792a7dc02bc3d1254 #2.0.0
      with:
        app-id: ${{ secrets.MOBILE_CI_APP_ID }}
        private-key: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
        owner: gini

    - name: Configure the git client
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

        git remote set-url origin https://x-oauth-token:${GH_TOKEN}@github.com/gini/gini-mobile-ios.git
        git remote -v

    - name: Publish GiniCaptureSDK documentation to the release repo
      uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      with:
        lane: 'publish_docs'
        options: >
          { 
            "project_folder": "CaptureSDK",
            "package_folder": "GiniCaptureSDK",
            "version_file_path": "CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/GiniCaptureSDKVersion.swift",
            "documentation_title":"GiniCaptureSDK Reference",
            "is_stable_release": "${{ steps.branch.outputs.branch_name == 'main' }}",
            "git_tag": "${{ github.ref }}"
          }

    - name: archive documentation
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.0.0
      with:
        name: GiniCaptureSDKDocumentation
        path: CaptureSDK/GiniCaptureSDK/Documentation/Api              
