name: Publish docs for Health API Library

on:
  push:
    tags:
      - 'GiniHealthAPILibrary;[0-9]+.[0-9]+.[0-9]+;doc**'

jobs:
  publish:
    uses: ./.github/workflows/sdk.publish.docs.yml
    with:
      project_folder: 'HealthAPILibrary'
      package_folder: 'GiniHealthAPILibrary'
      version_file_path: 'HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift'
      documentation_title: 'GiniHealthAPILibrary Reference'
      git_tag: ${{ github.ref }}
      is_stable_release: true
    secrets:
      RELEASE_GITHUB_USER: ${{ secrets.RELEASE_GITHUB_USER }}
      RELEASE_GITHUB_PASSWORD: ${{ secrets.RELEASE_GITHUB_PASSWORD }}
      MOBILE_CI_APP_ID: ${{ secrets.MOBILE_CI_APP_ID }}
      MOBILE_CI_APP_PRIVATE_KEY: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
