name: Publish docs for Health API Library
permissions:
  contents: read
on:
  push:
    tags:
      - 'GiniHealthAPILibrary;[0-9]+.[0-9]+.[0-9]+;doc**'
  workflow_call:
    secrets:
      RELEASE_GITHUB_USER:
        required: true
      RELEASE_GITHUB_PASSWORD:
        required: true
  workflow_dispatch:
  
jobs:
  release-documentation:
    runs-on: macos-latest   
    steps:
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '16.4'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get branch name
      id: branch
      shell: bash
      run: |
        # Get the branch ref that contains the tag in github.ref
        # (github.ref contains the tag because this workflow is triggered by tags: 
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
        branch_ref=$(git branch -r --contains "${{ github.ref }}")
        # Remove "origin/" prefix from branch_ref and trim whitespace
        branch_name=$(echo ${branch_ref/origin\/} | tr -d '[:space:]')
        echo "{branch_name}={branch_name}" >> $GITHUB_OUTPUT
        echo "branch_name: $branch_name"

    - name: setup ruby
      uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.245.0
      with:
        ruby-version: '3.2.0'
        bundler-cache: true
    - name: Generate a token
      id: generate-token
      # available args: https://github.com/actions/create-github-app-token?tab=readme-ov-file
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.MOBILE_CI_APP_ID }}
        private-key: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
        owner: gini

      # useful references in the README on: https://github.com/actions/create-github-app-token 
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

    # (feel free to remove this comment before merging, just a note)
    # @Nadya this can probably work by passing in `x-oauth-token` as username to fastlane and GH_TOKEN as pass.
    # Otherwise, this handling will give it a clean-ish git conf.
    - name: Configure the git client
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        echo git config --local user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
        echo git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        git config --local user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
        git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        # We must ditch all the cred details the checkout action fills in
        # otherwise this conflicts with our basic auth passed in the remote and fails to push
        git config --local credential.helper ""
        git config --local --unset http.https://github.com/.extraheader || true
        git remote remove origin || true
        git remote add origin https://x-oauth-token:${GH_TOKEN}@github.com/gini/gini-mobile-ios.git
        git push origin HEAD:daniel-test-happy-days

    - name: Publish GiniHealthAPILibrary documentation to the release repo
      uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
      with:
        lane: 'publish_docs'
        options: >
          { 
            "project_folder": "HealthAPILibrary",
            "package_folder": "GiniHealthAPILibrary",
            "version_file_path": "HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift", 
            "documentation_title":"GiniHealthAPILibrary Reference",
            "is_stable_release": "true",
            "git_tag": "${{ github.ref }}",
            "ci": "true"
          }

    - name: archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: GiniHealthAPILibraryDocumentation
        path: HealthAPILibrary/GiniHealthAPILibrary/Documentation/Api              
