name: Publish SDK Docs (Reusable)

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      project_folder:
        description: 'The folder containing the project to document'
        required: true
        type: string
      package_folder:
        description: 'The folder containing the package'
        required: true
        type: string
      version_file_path:
        description: 'The path to the version file'
        required: true
        type: string
      documentation_title:
        description: 'The title for the documentation'
        required: true
        type: string
      git_tag:
        description: 'The Git tag for the release'
        required: true
        type: string
      is_stable_release:
        description: 'Indicates if this is a stable release'
        required: true
        type: boolean
    secrets:
      MOBILE_CI_APP_ID:
        required: true
      MOBILE_CI_APP_PRIVATE_KEY:
        required: true

  workflow_dispatch:
    inputs:
      project_folder:
        description: 'The folder containing the project to document'
        required: true
        type: string
      package_folder:
        description: 'The folder containing the package'
        required: true
        type: string
      version_file_path:
        description: 'The path to the version file'
        required: true
        type: string
      documentation_title:
        description: 'The title for the documentation'
        required: true
        type: string
      git_tag:
        description: 'The Git tag for the release'
        required: true
        type: string
      is_stable_release:
        description: 'Indicates if this is a stable release'
        required: true
jobs:
  release-documentation:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: '16.4'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.245.0
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@064492a9a1762067169d50c792a7dc02bc3d1254 #2.0.0
        with:
          app-id: ${{ secrets.MOBILE_CI_APP_ID }}
          private-key: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
          owner: gini

      - name: Configure the git client
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

          git remote set-url origin https://x-oauth-token:${GH_TOKEN}@github.com/gini/gini-mobile-ios.git

      - name: Publish documentation
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          lane: publish_docs
          options: >
            {
              "project_folder": "${{ inputs.project_folder }}",
              "package_folder": "${{ inputs.package_folder }}",
              "version_file_path": "${{ inputs.version_file_path }}",
              "documentation_title": "${{ inputs.documentation_title }}",
              "is_stable_release": ${{ inputs.is_stable_release }},
              "git_tag": "${{ inputs.git_tag }}",
              "ci": true
            }

      - name: Archive documentation
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.0.0
        with:
          name: ${{ inputs.package_folder }}Documentation
          path: ${{ inputs.project_folder }}/${{ inputs.package_folder }}/Documentation/Api
