name: Check Gini Utilites
on:
  pull_request:
   types: [opened, reopened, synchronize, ready_for_review]
   paths:
      - 'GiniComponents/GiniUtilites/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [GiniUtilites]
        destination: ['platform=iOS Simulator,OS=18.5,name=iPhone 16']
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '16.0'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check package GiniUtilites
      run: |
           cd GiniComponents/GiniUtilites
           swift package update

    - name: Build sdk targets
      run: |
        xcodebuild -workspace GiniMobile.xcworkspace -scheme "${{ matrix.target }}" -destination "${{ matrix.destination }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO